<?php
/**
 * CustomersAPIApiTest
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * B2B Operations API
 *
 * This application will be used by HaaS customers as an integration point with HAY Bank
 *
 * The version of the OpenAPI document: 0.0.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use OpenAPI\Client\Configuration;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomersAPIApiTest Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomersAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for blockCustomer
     *
     * Block Customer.
     *
     */
    public function testBlockCustomer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for changeHayCustomerStatus
     *
     * Update Customer status.
     *
     */
    public function testChangeHayCustomerStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createHayAccount
     *
     * Create Account for Customer - (To be DEPRECATED - Use POST /v1/accounts instead).
     *
     */
    public function testCreateHayAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createHayCustomer
     *
     * Create Customer.
     *
     */
    public function testCreateHayCustomer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountsForCustomerId
     *
     * Get Account by Customer ID.
     *
     */
    public function testGetAccountsForCustomerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllCustomers
     *
     * Get all Customers.
     *
     */
    public function testGetAllCustomers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCardsForCustomerId
     *
     * Get Cards by Customer ID.
     *
     */
    public function testGetCardsForCustomerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getHayCustomerById
     *
     * Get Customer by ID.
     *
     */
    public function testGetHayCustomerById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchCustomers
     *
     * Search Customers.
     *
     */
    public function testSearchCustomers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unblockCustomer
     *
     * Unblock Customer.
     *
     */
    public function testUnblockCustomer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCustomer
     *
     * Update Customer details.
     *
     */
    public function testUpdateCustomer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
