<?php
/**
 * CreateMandateRequestBody
 *
 * PHP version 8.1
 *
 * @package  Shaype\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * B2B Operations API
 *
 * This application will be used by HaaS customers as an integration point with HAY Bank
 *
 * The version of the OpenAPI document: 0.0.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shaype\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Shaype\Client\ObjectSerializer;

/**
 * CreateMandateRequestBody Class Doc Comment
 *
 * @description Body of a request to add mandate.
 * @package  Shaype\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateMandateRequestBody implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'CreateMandateRequestBody';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'creditor_details' => '\Shaype\Client\Model\CreateCreditorDetailsDto',
        'debtor_details' => '\Shaype\Client\Model\CreateDebtorDetailsDto',
        'description' => 'string',
        'idempotency_key' => 'string',
        'payment_terms' => '\Shaype\Client\Model\CreatePaymentTermsDto',
        'purpose_code' => 'string',
        'resolution_requested_by' => 'string',
        'transfer_arrangement' => 'string',
        'validity_end_date' => '\DateTime',
        'validity_start_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'creditor_details' => null,
        'debtor_details' => null,
        'description' => null,
        'idempotency_key' => 'uuid',
        'payment_terms' => null,
        'purpose_code' => null,
        'resolution_requested_by' => null,
        'transfer_arrangement' => null,
        'validity_end_date' => 'date',
        'validity_start_date' => 'date'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'creditor_details' => false,
        'debtor_details' => false,
        'description' => false,
        'idempotency_key' => false,
        'payment_terms' => false,
        'purpose_code' => false,
        'resolution_requested_by' => false,
        'transfer_arrangement' => false,
        'validity_end_date' => false,
        'validity_start_date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'creditor_details' => 'creditorDetails',
        'debtor_details' => 'debtorDetails',
        'description' => 'description',
        'idempotency_key' => 'idempotencyKey',
        'payment_terms' => 'paymentTerms',
        'purpose_code' => 'purposeCode',
        'resolution_requested_by' => 'resolutionRequestedBy',
        'transfer_arrangement' => 'transferArrangement',
        'validity_end_date' => 'validityEndDate',
        'validity_start_date' => 'validityStartDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'creditor_details' => 'setCreditorDetails',
        'debtor_details' => 'setDebtorDetails',
        'description' => 'setDescription',
        'idempotency_key' => 'setIdempotencyKey',
        'payment_terms' => 'setPaymentTerms',
        'purpose_code' => 'setPurposeCode',
        'resolution_requested_by' => 'setResolutionRequestedBy',
        'transfer_arrangement' => 'setTransferArrangement',
        'validity_end_date' => 'setValidityEndDate',
        'validity_start_date' => 'setValidityStartDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'creditor_details' => 'getCreditorDetails',
        'debtor_details' => 'getDebtorDetails',
        'description' => 'getDescription',
        'idempotency_key' => 'getIdempotencyKey',
        'payment_terms' => 'getPaymentTerms',
        'purpose_code' => 'getPurposeCode',
        'resolution_requested_by' => 'getResolutionRequestedBy',
        'transfer_arrangement' => 'getTransferArrangement',
        'validity_end_date' => 'getValidityEndDate',
        'validity_start_date' => 'getValidityStartDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const PURPOSE_CODE_MORTGAGE = 'MORTGAGE';
    public const PURPOSE_CODE_UTILITY = 'UTILITY';
    public const PURPOSE_CODE_LOAN = 'LOAN';
    public const PURPOSE_CODE_DEPENDANT = 'DEPENDANT';
    public const PURPOSE_CODE_GAMBLING = 'GAMBLING';
    public const PURPOSE_CODE_RETAIL = 'RETAIL';
    public const PURPOSE_CODE_SALARY = 'SALARY';
    public const PURPOSE_CODE_PERSONAL = 'PERSONAL';
    public const PURPOSE_CODE_GOVERNMENT = 'GOVERNMENT';
    public const PURPOSE_CODE_PENSION = 'PENSION';
    public const PURPOSE_CODE_TAX = 'TAX';
    public const PURPOSE_CODE_OTHER = 'OTHER';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPurposeCodeAllowableValues()
    {
        return [
            self::PURPOSE_CODE_MORTGAGE,
            self::PURPOSE_CODE_UTILITY,
            self::PURPOSE_CODE_LOAN,
            self::PURPOSE_CODE_DEPENDANT,
            self::PURPOSE_CODE_GAMBLING,
            self::PURPOSE_CODE_RETAIL,
            self::PURPOSE_CODE_SALARY,
            self::PURPOSE_CODE_PERSONAL,
            self::PURPOSE_CODE_GOVERNMENT,
            self::PURPOSE_CODE_PENSION,
            self::PURPOSE_CODE_TAX,
            self::PURPOSE_CODE_OTHER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('creditor_details', $data ?? [], null);
        $this->setIfExists('debtor_details', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('idempotency_key', $data ?? [], null);
        $this->setIfExists('payment_terms', $data ?? [], null);
        $this->setIfExists('purpose_code', $data ?? [], null);
        $this->setIfExists('resolution_requested_by', $data ?? [], null);
        $this->setIfExists('transfer_arrangement', $data ?? [], null);
        $this->setIfExists('validity_end_date', $data ?? [], null);
        $this->setIfExists('validity_start_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['creditor_details'] === null) {
            $invalidProperties[] = "'creditor_details' can't be null";
        }
        if ($this->container['debtor_details'] === null) {
            $invalidProperties[] = "'debtor_details' can't be null";
        }
        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 140)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 140.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) < 0)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['idempotency_key'] === null) {
            $invalidProperties[] = "'idempotency_key' can't be null";
        }
        if ($this->container['payment_terms'] === null) {
            $invalidProperties[] = "'payment_terms' can't be null";
        }
        if ($this->container['purpose_code'] === null) {
            $invalidProperties[] = "'purpose_code' can't be null";
        }
        $allowedValues = $this->getPurposeCodeAllowableValues();
        if (!is_null($this->container['purpose_code']) && !in_array($this->container['purpose_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'purpose_code', must be one of '%s'",
                $this->container['purpose_code'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['validity_start_date'] === null) {
            $invalidProperties[] = "'validity_start_date' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets creditor_details
     *
     * @return \Shaype\Client\Model\CreateCreditorDetailsDto
     */
    public function getCreditorDetails(): \Shaype\Client\Model\CreateCreditorDetailsDto
    {
        return $this->container['creditor_details'];
    }

    /**
     * Sets creditor_details
     *
     * @param \Shaype\Client\Model\CreateCreditorDetailsDto $creditor_details creditor_details
     *
     * @return $this
     */
    public function setCreditorDetails(\Shaype\Client\Model\CreateCreditorDetailsDto $creditor_details): static
    {
        if (is_null($creditor_details)) {
            throw new InvalidArgumentException('non-nullable creditor_details cannot be null');
        }
        $this->container['creditor_details'] = $creditor_details;

        return $this;
    }

    /**
     * Gets debtor_details
     *
     * @return \Shaype\Client\Model\CreateDebtorDetailsDto
     */
    public function getDebtorDetails(): \Shaype\Client\Model\CreateDebtorDetailsDto
    {
        return $this->container['debtor_details'];
    }

    /**
     * Sets debtor_details
     *
     * @param \Shaype\Client\Model\CreateDebtorDetailsDto $debtor_details debtor_details
     *
     * @return $this
     */
    public function setDebtorDetails(\Shaype\Client\Model\CreateDebtorDetailsDto $debtor_details): static
    {
        if (is_null($debtor_details)) {
            throw new InvalidArgumentException('non-nullable debtor_details cannot be null');
        }
        $this->container['debtor_details'] = $debtor_details;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description A mandate description.
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 140)) {
            throw new InvalidArgumentException('invalid length for $description when calling CreateMandateRequestBody., must be smaller than or equal to 140.');
        }
        if ((mb_strlen($description) < 0)) {
            throw new InvalidArgumentException('invalid length for $description when calling CreateMandateRequestBody., must be bigger than or equal to 0.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets idempotency_key
     *
     * @return string
     */
    public function getIdempotencyKey(): string
    {
        return $this->container['idempotency_key'];
    }

    /**
     * Sets idempotency_key
     *
     * @param string $idempotency_key Idempotency key generated by the client of the API. Used for request duplication check.
     *
     * @return $this
     */
    public function setIdempotencyKey(string $idempotency_key): static
    {
        if (is_null($idempotency_key)) {
            throw new InvalidArgumentException('non-nullable idempotency_key cannot be null');
        }
        $this->container['idempotency_key'] = $idempotency_key;

        return $this;
    }

    /**
     * Gets payment_terms
     *
     * @return \Shaype\Client\Model\CreatePaymentTermsDto
     */
    public function getPaymentTerms(): \Shaype\Client\Model\CreatePaymentTermsDto
    {
        return $this->container['payment_terms'];
    }

    /**
     * Sets payment_terms
     *
     * @param \Shaype\Client\Model\CreatePaymentTermsDto $payment_terms payment_terms
     *
     * @return $this
     */
    public function setPaymentTerms(\Shaype\Client\Model\CreatePaymentTermsDto $payment_terms): static
    {
        if (is_null($payment_terms)) {
            throw new InvalidArgumentException('non-nullable payment_terms cannot be null');
        }
        $this->container['payment_terms'] = $payment_terms;

        return $this;
    }

    /**
     * Gets purpose_code
     *
     * @return string
     */
    public function getPurposeCode(): string
    {
        return $this->container['purpose_code'];
    }

    /**
     * Sets purpose_code
     *
     * @param string $purpose_code The purpose of this mandate.  * **MORTGAGE**: Mortgage payments.  * **UTILITY**: Utility payments.  * **LOAN**: Loan payments.  * **DEPENDANT**: Dependant support payments.  * **GAMBLING**: Gambling payments.  * **RETAIL**: Retail payments.  * **SALARY**: Salary payments.  * **PERSONAL**: Personal payments.  * **GOVERNMENT**: Government payments.  * **PENSION**: Pension payments.  * **TAX**: Tax payments.  * **OTHER**: Other service payments.
     *
     * @return $this
     */
    public function setPurposeCode(string $purpose_code): static
    {
        if (is_null($purpose_code)) {
            throw new InvalidArgumentException('non-nullable purpose_code cannot be null');
        }
        $allowedValues = $this->getPurposeCodeAllowableValues();
        if (!in_array($purpose_code, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'purpose_code', must be one of '%s'",
                    $purpose_code,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['purpose_code'] = $purpose_code;

        return $this;
    }

    /**
     * Gets resolution_requested_by
     *
     * @return string|null
     */
    public function getResolutionRequestedBy(): ?string
    {
        return $this->container['resolution_requested_by'];
    }

    /**
     * Sets resolution_requested_by
     *
     * @param string|null $resolution_requested_by Date time in UTC format yyyy-MM-dd'T'hh:mm:ss.sss'Z' e.g. 2023-09-10T10:00:00.000Z (Optional).
     *
     * @return $this
     */
    public function setResolutionRequestedBy(?string $resolution_requested_by): static
    {
        if (is_null($resolution_requested_by)) {
            throw new InvalidArgumentException('non-nullable resolution_requested_by cannot be null');
        }
        $this->container['resolution_requested_by'] = $resolution_requested_by;

        return $this;
    }

    /**
     * Gets transfer_arrangement
     *
     * @return string|null
     */
    public function getTransferArrangement(): ?string
    {
        return $this->container['transfer_arrangement'];
    }

    /**
     * Sets transfer_arrangement
     *
     * @param string|null $transfer_arrangement Indication of future transfer date, conditions of sale and requirement to hold funds.
     *
     * @return $this
     */
    public function setTransferArrangement(?string $transfer_arrangement): static
    {
        if (is_null($transfer_arrangement)) {
            throw new InvalidArgumentException('non-nullable transfer_arrangement cannot be null');
        }
        $this->container['transfer_arrangement'] = $transfer_arrangement;

        return $this;
    }

    /**
     * Gets validity_end_date
     *
     * @return \DateTime|null
     */
    public function getValidityEndDate(): ?\DateTime
    {
        return $this->container['validity_end_date'];
    }

    /**
     * Sets validity_end_date
     *
     * @param \DateTime|null $validity_end_date The date when the mandate stops being valid.
     *
     * @return $this
     */
    public function setValidityEndDate(?\DateTime $validity_end_date): static
    {
        if (is_null($validity_end_date)) {
            throw new InvalidArgumentException('non-nullable validity_end_date cannot be null');
        }
        $this->container['validity_end_date'] = $validity_end_date;

        return $this;
    }

    /**
     * Gets validity_start_date
     *
     * @return \DateTime
     */
    public function getValidityStartDate(): \DateTime
    {
        return $this->container['validity_start_date'];
    }

    /**
     * Sets validity_start_date
     *
     * @param \DateTime $validity_start_date The date when the mandate becomes valid.
     *
     * @return $this
     */
    public function setValidityStartDate(\DateTime $validity_start_date): static
    {
        if (is_null($validity_start_date)) {
            throw new InvalidArgumentException('non-nullable validity_start_date cannot be null');
        }
        $this->container['validity_start_date'] = $validity_start_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


